language: node_js
env:
  - 'DATABASE_URL=postgresql://localhost:5432/taxis'
node_js:
  - 12
before_script:
  - psql -c 'create database taxis;' -U postgres
  - psql -U postgres -d taxis -a -f ./sql/data.sql
services:
  - postgresql
